name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
    - name: Build Artifact
      run: |
        npm install
        npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: '@passwordlessdev-passwordless-client'
        path: |
          dist
          package.json

    - name: Trigger NPM Release
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PAT }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/bitwarden/passwordless-devops/actions/workflows/passwordless-client-js.yml/dispatches \
        -d '{"ref":"master","inputs":{"repository":"${{github.repository}}","name":"@passwordlessdev-passwordless-client","run-id":"${{github.run_id}}"}}'
