name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
    - name: Build
      run: |
        npm install
        npm run build --if-present
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: '@passwordlessdev-passwordless-client'
        path: |
          dist
          package.json

    - name: Trigger NPM Release
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PAT }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/jonashendrickx/passwordless-devops/actions/workflows/passwordless-client-js.yml/dispatches \
        -d '{"owner": "jonashendrickx","repository":"passwordless-client-js", "workflow-id": "passwordless-client-js.yml", "inputs": { "name": "@passwordlessdev-passwordless-client", "run-id": "${{ github.run_id }}" } }'
