name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Trigger Repository Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "release", "client_payload": { "repository": "jonashendrickx/passwordless-client-js", "ref": "${{ github.event.release.tag_name }}" }}' \
          https://api.github.com/repos/jonashendrickx/passwordless-devops/dispatches
