name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
    - name: Build
      run: |
        npm install
        npm run build --if-present
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          dist
          package.json
    - name: Trigger NPM Release
      uses: lasith-kg/dispatch-workflow@v1
      with:
        dispatch-method: workflow_dispatch
        repo: 'passwordless-client-js'
        owner: ${{ github.repository_owner }}
        workflow: ${{ github.workflow }}
        token: ${{ secrets.PAT }}
