name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.1
    - name: Build Artifact
      run: |
        npm ci
        npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 #v4
      with:
        name: '@passwordlessdev-passwordless-client'
        path: |
          dist
          package.json

    - name: Dispatch NPM Release
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
      run: >
        gh workflow run passwordless-client-js
        --repo bitwarden/passwordless-devops
        --field repository=${{ github.repository }}
        --field run-id=${{ github.run_id }}
        --field name=@passwordlessdev-passwordless-client

